2025-02-10 08:53:27 INFO: Application startup [in /Users/amin/code/study/wecometest/app.py:66]
2025-02-10 08:53:27 INFO: 开始执行定时任务刷新缓存: 2025-02-10 08:53:27.518994 [in /Users/amin/code/study/wecometest/scheduler.py:23]
2025-02-10 08:53:27 INFO: 从API获取每日建议数据 [in /Users/amin/code/study/wecometest/solar_terms_api.py:71]
2025-02-10 08:53:28 ERROR: 定时任务执行失败: {'code': -1, 'message': '未找到建议信息', 'data': None} [in /Users/amin/code/study/wecometest/scheduler.py:31]
2025-02-10 08:53:28 INFO: 定时任务调度器已启动 [in /Users/amin/code/study/wecometest/scheduler.py:78]
2025-02-10 08:55:05 INFO: Request: GET http://localhost:8090/api/almanac?date=2025-02-10 - Response: 200 OK [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-10 09:03:26 INFO: Request: GET http://localhost:8090/api/almanac?date=2025-02-10 - Response: 200 OK [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-10 14:56:38 INFO: Application startup [in /Users/amin/code/study/wecometest/app.py:66]
2025-02-10 14:56:38 INFO: 开始执行定时任务刷新缓存: 2025-02-10 14:56:38.942265 [in /Users/amin/code/study/wecometest/scheduler.py:23]
2025-02-10 14:56:38 INFO: 从API获取每日建议数据 [in /Users/amin/code/study/wecometest/solar_terms_api.py:71]
2025-02-10 14:56:39 ERROR: 定时任务执行失败: {'code': -1, 'message': '未找到建议信息', 'data': None} [in /Users/amin/code/study/wecometest/scheduler.py:31]
2025-02-10 14:56:39 INFO: 定时任务调度器已启动 [in /Users/amin/code/study/wecometest/scheduler.py:78]
2025-02-10 14:57:15 INFO: Request: GET http://localhost:8090/ws/chat - Response: 400 BAD REQUEST [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-10 14:57:28 ERROR: Exception on /ws/chat [GET] [in /Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask_sock/__init__.py", line 59, in websocket_route
    ws = Server(request.environ, **current_app.config.get(
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/simple_websocket/ws.py", line 290, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
2025-02-10 14:57:28 INFO: Request: GET http://localhost:8090/ws/chat - Response: 500 INTERNAL SERVER ERROR [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-10 14:57:57 ERROR: Exception on /ws/chat [GET] [in /Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask_sock/__init__.py", line 59, in websocket_route
    ws = Server(request.environ, **current_app.config.get(
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/simple_websocket/ws.py", line 290, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
2025-02-10 14:57:57 INFO: Request: GET http://localhost:8090/ws/chat - Response: 500 INTERNAL SERVER ERROR [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-10 14:57:59 ERROR: Exception on /ws/chat [GET] [in /Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask_sock/__init__.py", line 59, in websocket_route
    ws = Server(request.environ, **current_app.config.get(
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/simple_websocket/ws.py", line 290, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
2025-02-10 14:57:59 INFO: Request: GET http://localhost:8090/ws/chat - Response: 500 INTERNAL SERVER ERROR [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-10 14:57:59 ERROR: Exception on /ws/chat [GET] [in /Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask_sock/__init__.py", line 59, in websocket_route
    ws = Server(request.environ, **current_app.config.get(
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/simple_websocket/ws.py", line 290, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
2025-02-10 14:57:59 INFO: Request: GET http://localhost:8090/ws/chat - Response: 500 INTERNAL SERVER ERROR [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-10 14:58:12 ERROR: Exception on /ws/chat [GET] [in /Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/flask_sock/__init__.py", line 59, in websocket_route
    ws = Server(request.environ, **current_app.config.get(
  File "/Users/amin/code/study/wecometest/venv/lib/python3.9/site-packages/simple_websocket/ws.py", line 290, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
2025-02-10 14:58:12 INFO: Request: GET http://localhost:8090/ws/chat?message - Response: 500 INTERNAL SERVER ERROR [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-11 10:25:56 INFO: Application startup [in /Users/amin/code/study/wecometest/app.py:66]
2025-02-11 10:25:56 INFO: 开始执行定时任务刷新缓存: 2025-02-11 10:25:56.509231 [in /Users/amin/code/study/wecometest/scheduler.py:23]
2025-02-11 10:25:56 INFO: 从API获取每日建议数据 [in /Users/amin/code/study/wecometest/solar_terms_api.py:72]
2025-02-11 10:25:57 ERROR: 定时任务执行失败: {'code': -1, 'message': '未找到建议信息', 'data': None} [in /Users/amin/code/study/wecometest/scheduler.py:31]
2025-02-11 10:25:57 INFO: 定时任务调度器已启动 [in /Users/amin/code/study/wecometest/scheduler.py:78]
2025-02-11 10:47:44 INFO: Request: GET http://localhost:8090/api/food_advice?province=山东&current_term=立春 - Response: 200 OK [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-11 10:52:40 INFO: Request: GET http://localhost:8090/api/food_advice?province=山东&current_term=立春 - Response: 200 OK [in /Users/amin/code/study/wecometest/app.py:73]
2025-02-11 10:57:24 INFO: Request: GET http://localhost:8090/api/food_advice?province=山东&current_term=立春 - Response: 200 OK [in /Users/amin/code/study/wecometest/app.py:73]
